Algoritmo "Exercício 6"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Hiram Amaral
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : João Víctor Martins Moreira.
// Data atual  : 08/04/2022
Var
   altura, base: real

Inicio
   escreva("Informe a altura: ")
   leia(altura)
   
   escreva("Informe a base: ")
   leia(base)
   
   escreval("A area é: ", altura*base)

Fimalgoritmo